


spring.application.name=TravelSpringMvcApp

server.port=${PORT:3306}

spring.datasource.url=${mysql://root:ZhjhPyosGAnJJOMpCiDSReNKtdDEqsUc@mysql.railway.internal:3306/railway}
spring.datasource.username=${root}
spring.datasource.password=${ZhjhPyosGAnJJOMpCiDSReNKtdDEqsUc}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
